language: java
jdk:
- openjdk11
script:
- "./gradlew build"
env:
  global:
  - OSSRH_JIRA_USERNAME=navikt
  - GPG_KEY_NAME=navikt
  - secure: pXhSChWBvXNPln4YMNmrhHXbxK1Q1lUEjP5sdyo9Wk34aX0NeSPPbmmskUsecdM5ICqBDKJdvnptpGsB/F0PmPumDzMCIJ9Qfhmxz0kRSK1ni7FB2ocZeWAcdPmeiBUqb4kKAp/bKVG2kV4UJJsVQetT47wMTbRQc5QKDi9LCRf84PWUSOyn/FY/zoLsn+U6VOCU7Re87ua1RbqVjgDQE683RhP6r9dcbygoSNiBQV0OcqjSlb9KN0ag5bMRsMdY1jRJ5/SWHpTFWHOvwD3AxVKNhp92+MFca/dFsx/rU83H3WpN9tqdfsgPN21wPx+GpCStS/9iPfB7N9BRabEj6pbrKb4fIgU9TAHfOmTu45jorwfPmwAQZtSn21aKjUFw5WR+1VSKqeLlpnGmgrYYjb01xwtW0Rw9NASjAzoVoL5guCkEnStrkAtz2kEuVsgB6SBxjIqm2gZPXgzgQ6PoxA3MZ66CejJGmKzAuTNUYQwchu0OCTW+j1pU34myWF3y3dks9pbhjwoytxx8FqKi/1OXCnOdtX1vGN78viPixd68DZ8FTEk+3iAGvPgMFUCa6JYP3vDscRzyD5Bpmcrh9nMq3M14ve/QGY+OHWPGlObEZvT9En4ZQX0FXo9qKxc9GBsdy0JGcQDNsV2jYDoEVoU4aLARlYwRqnMK+LUMA94=
  - secure: RJUx1aL341Ji/3qcWLIp9OefHrJerL/daTbH4wyxxyxElSX9xv3kJJKA1aqPeyWeC4qJtRrMAcAJvGCCmKYwxqiQ0elbJLnHBIeg3WoDP/OTeoNRcjCXYrdKJl/iIif2RIE4GaKE6upOdJl8W2tliOfMyT0gWYwntePFWyZoEtnc8PlJOJ51fT7m0sxdlDHLdSUzMde8GB+Uafsw7JRocKCIb8JZ1dW7dn4U+SsKLMa3d9nForu+guyYL3KKOsZmeccDOBDJpdbs/3a8agHpTxC0jT0AjfLJE7GuPi2yBlQMqzATrLDM5sS/ll8S5n1Lb2SWzxeRcYpz7+wZKGqhVJYGpQDnkSmM4tarrcQBp3VrCcPoGbaVWh8VPIu+IaKm0yjsLNmT+dKwiM8c9x7hQ57TcBm+12nqPOCHjkZKns+1tEqV1GTswdhv0zalfuB8Bx76Ar1PSR08f+Vm1ov0ast162OrHrvZvXrtGO+gT8BYNsqcljgKlJCgH8i8G9rid0ivunEJ45m3VfIEEdD71TZhvA/7C/nO9NKPCeS3XY+JfzdL7mrCaKmT8qdHwbijP8BzqKjazdZs+EZwGVSSec1mpznMgnleH0ceB8NV64efty46w0C08WvvH/7xq1z6kM0SdYOpgvKlIUVr2245SibNWuqUPGM7ccKORiuV6ko=
before_install:
- openssl aes-256-cbc -K $encrypted_9d0bda201803_key -iv $encrypted_9d0bda201803_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
- gpg --fast-import travis/codesigning.asc
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: script
  script: "./gradlew publish --info --stacktrace getStagingProfile"
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: DuTfh+WDqgDGZK3Tj7b5y9JvzLDeyJOLCPUerNMm7kfcDtNKzHpYMiZILK6Yf2l8Q4qk03BXAYdwPu2QTlFYKxmttPQQNr36H7qa3XUDV685AgzQQEIXO4uy8xMQjDUi4kRYMnaw15ycuVToXEwmHyrG7e5p8440dR44UJJkJCiGENy1e4vq0PKpJBaoGGWBVVicr9kc/A0RtQPaeRP/JEAKa/f2uLfva+rmlDQpWZxg74/9mdqfmWvymxWcz4/lspxGYXKrxVOgem+2MqbidU/4Wta2Woh5OwFcTeehRwhr16mF9DxqMfAEepERCBR/2ly3MJR9QQg2ux6WN+x2Vb7t+XDgdWjP0MfXA1TTOg2q52ayuU6/8ofotfDLhcD8QvlKFNfp3XL1EHZoXIZ7th4oLxadwfNZ6Cx3FQLktQL4nhork4u7/LKriK1AXG2b50y4Vvrdzzq9Ppnagh01q1sYzpU933PFMXv0HBqafi/bExZoqB6SNexoS6tAjWtTqrPUcbpN08L1DDSPwyGTaxmTrapa33iwykwVzo4cOB58P0PF7q08bBjq+SI9l0t7WFX8Q9VUGKmhrE5RF31BwRQ+mu4vQEQiqe3Lt+u+QM8Xv9TbswTjsUAXMXs6Fb/2SkgZFLBCRmv1lMe50ek6lTJoJeifOXTJVP32d6fl9bo=
  on_success: change
  on_failure: always
  on_pull_requests: false
